name: Dockerize

on:
  push:
    branches:
      - main

jobs:
  buildingimages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Simply test
        run: echo "hello world"

      - name: display image
        run: docker images

      - name: elasticsearch image
        run: docker pull docker.elastic.co/elasticsearch/elasticsearch:8.8.1

      - name: display elastic image
        run: docker images

      - name: setting up java maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd cricket
          mvn --batch-mode --update-snapshots verify

#      - name: staging file
#        run: mkdir staging && cp cricket/target/*.jar staging
#        uses: actions/upload-artifact@v4
#        with:
#          name: Package
#          path: staging

#      - name: build spring boot image
#        run: docker build -t spring-app .
#
#      - name: display spring-app image
#        run: docker images

      - name: Login to  Docker hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: pragadeesht/testrepo:latest

